---
- block:
    - name: Deploy prometheus server credentials
      tags:
        - ponyta
      copy:
        content: |
          {{ prometheus_credentials_content | default('admin') }}
        dest: "{{ prometheus_credentials_filepath }}"
        mode: "0664"
        owner: "{{ ponyta_user | default('root') }}"
        group: "{{ ponyta_user | default('root') }}"
      when: prometheus_enabled or grafana_enabled

    - name: Ensure htpasswd is installed
      tags:
        - htpasswd
        - ponyta
      ansible.builtin.package:
        name: apache2-utils
        state: present

    - name: Check if web config exists
      tags:
        - htpasswd
        - ponyta
      ansible.builtin.stat:
        path: "{{ prometheus_web_filepath }}"
      register: web_config_stat

    - name: Generate bcrypt hashes for each user
      tags:
        - ponyta
        - htpasswd
        # - never
      ansible.builtin.shell:
        cmd: "htpasswd -bnBC 12 {{ item.key }} {{ item.value }} | head -n1 | cut -d: -f2"
      register: password_hashes
      loop: "{{ prometheus_users | dict2items }}"
      changed_when: false
      when:
        - not web_config_stat.stat.exists or prometheus_force_password_regenerate

    - name: Create hashed users dictionary
      tags:
        - htpasswd
        - ponyta
      ansible.builtin.set_fact:
        prometheus_hashed_users: "{{ {} }}"

    - name: Build hashed users dictionary
      tags:
        - htpasswd
        - ponyta
      ansible.builtin.set_fact:
        prometheus_hashed_users: "{{ prometheus_hashed_users | combine({item.item.key: item.stdout}) }}"
      loop: "{{ password_hashes.results }}"
      when:
        - password_hashes.results is defined
        - password_hashes is not skipped

    - name: Create Prometheus web configuration with encrypted passwords
      tags:
        - htpasswd
        - ponyta
      ansible.builtin.template:
        src: web.j2
        dest: "{{ prometheus_web_filepath }}"
        mode: "0664"
        owner: "{{ ponyta_user | default('root') }}"
        group: "{{ ponyta_user | default('root') }}"
      when:
        - password_hashes.results is defined
        - password_hashes is not skipped
