---
- block:
    - name: Deploy SNMP targets on disk
      template:
        src: "targets/{{ filename }}.j2"
        dest: "{{ prometheus_default_dir }}/{{ filename }}.json"
        lstrip_blocks: true
        trim_blocks: true
        mode: "0664"
        owner: "{{ ponyta_user | default('root') }}"
        group: "{{ ponyta_user | default('root') }}"
      when: snmp_targets | length > 0

    - name: Set fact after successfully SNMP targets deployment
      set_fact:
        snmp_targets_deployed: true
      when: snmp_targets | length > 0
  when:
    - snmp_exporter_enabled
    - snmp_targets_deployed is not defined

- block:
    - name: Destroy SNMP targets from disk
      file:
        path: "{{ prometheus_default_dir }}/{{ filename }}.json"
        state: absent
  when:
    - not snmp_exporter_enabled
