---
- name: Clone Git repository for wg_easy
  become: true
  block:
    - name: Update apt cache
      tags:
        - git
        - wg_easy
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt"

    - name: Install git if not present
      tags:
        - git
        - wg_easy
      package:
        name: git
        state: present
      when: ansible_pkg_mgr != "unknown"

    - name: Set global 'safe.directory' to prevent Git warnings
      tags:
        - git
        - wg_easy
      ansible.builtin.git_config:
        name: safe.directory
        scope: global
        value: "{{ wg_default_dir }}"
      when: ansible_pkg_mgr != "unknown"

    - name: Check if Git repository already exists
      tags:
        - git
        - wg_easy
      stat:
        path: "{{ git_clone_path }}/.git"
      register: git_repo_exists

    - name: Clone Git repository
      tags:
        - git
        - wg_easy
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_clone_path }}"
        version: "{{ git_branch }}"
        clone: true
        update: true
        force: yes
      when: not git_repo_exists.stat.exists

    - name: Set mode for Git repository
      tags:
        - git
        - wg_easy
      file:
        path: "{{ git_clone_path }}"
        owner: "{{ wg_easy_user | default('root') }}"
        group: "{{ wg_easy_user | default('root') }}"
        recurse: true
      when: not git_repo_exists.stat.exists

    - name: Update existing Git repository
      tags:
        - force_update_git_repo
        - never
      git:
        clone: false
        repo: "{{ git_repo_url }}"
        dest: "{{ git_clone_path }}"
        version: "{{ git_branch }}"
        update: true
        force: true
      when: git_repo_exists.stat.exists
  rescue:
    - name: Failed to clone or update Git repository
      tags:
        - wg_easy
        - git
      failed_when: true
      debug:
        msg:
          - "Failed to clone or update the Git repository from {{ git_repo_url }} to {{ git_clone_path }}"
          - "Reason: {{ ansible_failed_result.msg }}"
