---
- block:
    - name: Create wg_easy directories
      tags:
        - wg_dirs
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ wg_user }}"
        group: "{{ wg_user }}"
      with_items:
        - "{{ wg_default_dir }}"

- name: Import tasks for clone from git
  import_tasks: clone_from_git.yml

- name: Import tasks for verify network settings
  tags:
    - always
  import_tasks: network.yml
  when: not wg_shared_network

- name: Generate compose file ({{ service_name }})
  tags:
    - wg_easy_generate
  template:
    src: compose.yml.j2
    dest: "{{ wg_compose_file }}"
    trim_blocks: true
    lstrip_blocks: true
    mode: "0644"
    owner: "{{ wg_user }}"
    group: "{{ wg_user }}"

- block:
    - name: Enable deployed docker services
      tags:
        - wg_easy_docker
      community.docker.docker_compose_v2:
        project_src: "{{ wg_default_dir }}"
        files:
          - "{{ wg_compose_file }}"
        state: present
        services: "{{ service_name }}"
      register: enable_services_result
      when:
        - "'wg_easy_docker_restart' not in ansible_run_tags"
        - wg_easy_enabled

    - name: Disable docker services (if enabled)
      tags:
        - wg_easy_docker
      community.docker.docker_compose_v2:
        project_src: "{{ wg_default_dir }}"
        state: absent
        services: "{{ service_name }}"
      register: disable_services_result
      when:
        - not wg_easy_enabled

    - name: Restart deployed docker services
      tags:
        - wg_easy_docker_restart
      community.docker.docker_compose_v2:
        project_src: "{{ wg_default_dir }}"
        state: restarted
        services: "{{ service_name }}"
      register: restart_services_result
      when:
        - "'wg_easy_docker_restart' in ansible_run_tags"
        - wg_easy_enabled

    - name: Get running services
      tags:
        - debug
      ansible.builtin.command:
        cmd: "docker compose ps --services --filter 'status=running'"
        chdir: "{{ wg_default_dir }}"
      register: service_check

    - name: Display running services
      tags:
        - debug
      debug:
        var: service_check.stdout_lines

  rescue:
    - name: Failed operations with wg-easy docker services
      tags:
        - always
      debug:
        msg:
          - "Docker operations for wg_easy failed. Check previous tasks for details."
          - "{{ ansible_failed_result.msg }}"
